"""Shared export definitions for the :mod:`bot` package."""

from __future__ import annotations

SERVICES_EXPORTS = [
    "list_my_panels_admin",
    "list_panels_for_agent",
    "create_service",
    "list_services",
    "get_service",
    "list_service_panel_ids",
    "set_service_panels",
    "list_agents_by_service",
    "list_local_users_by_service",
    "set_agent_service",
    "resolve_local_user_owner",
    "set_local_user_service",
    "propagate_service_panels",
    "list_presets",
    "create_preset",
    "delete_preset",
    "get_preset",
    "update_preset",
    "upsert_app_user",
    "get_app_key",
    "upsert_local_user",
    "save_link",
    "remove_link",
    "list_linked_panel_ids",
    "map_linked_remote_usernames",
    "get_local_user",
    "search_local_users",
    "list_all_local_users",
    "count_local_users",
    "update_limit",
    "reset_used",
    "renew_user",
    "list_user_links",
    "delete_local_user",
    "delete_user",
    "set_panel_sub_url",
    "get_panel",
    "get_panel_disabled_names",
    "set_panel_disabled_names",
    "get_panel_disabled_nums",
    "set_panel_disabled_nums",
    "list_panel_links",
    "delete_panel_and_cleanup",
    "upsert_agent",
    "get_agent",
    "list_agents",
    "list_agent_panel_ids",
    "set_agent_panels",
    "sync_user_panels",
    "sync_user_panels_async",
]

__all__ = ["SERVICES_EXPORTS"]
